### ISSUE TITLE
Init routine for smartmirror directory

### ISSUE THREAD

**Issue by ventos** [veecue/pacman-smartmirror#12]
Add functionality to initialize smartmirror with all packages installed on the target user machine to reduce the setup timespan smartmirror needs to pipe trough unknown packages while adding them to its directory and cache.
could look something like this  
```
pacman -Q | smartmirror-client raspi.local 
```

**Comment by rossmeier** [comment]
Would be a simple bash script. To list all packages at least with remote repo and version (arch to be determined):
  `printf -v installed '[%s]' "$(gettext installed)"`          
  `pacman -Sl | awk -v i="$installed" '$NF == i { print $1,$2,$3 }'`
